[Hart85] Fix UnicodeDecodeError
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 164: character maps to <undefined>

In Python3, the pickle module expects the underlying file objects to accept or return bytes

	pickle_in = open(filename, 'rb')